/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import {
  RouterHistory,
  MatchResults,
} from '@stencil/router';

import {
  AppHome as AppHome
} from './components/app-home/app-home';

declare global {
  interface HTMLAppHomeElement extends AppHome, HTMLElement {
  }
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    "app-home": HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-home": JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {
      history?: RouterHistory;
    }
  }
}


import {
  AppMessages as AppMessage
} from './components/app-message/app-message';

declare global {
  interface HTMLAppMessageElement extends AppMessage, HTMLElement {
  }
  var HTMLAppMessageElement: {
    prototype: HTMLAppMessageElement;
    new (): HTMLAppMessageElement;
  };
  interface HTMLElementTagNameMap {
    "app-message": HTMLAppMessageElement;
  }
  interface ElementTagNameMap {
    "app-message": HTMLAppMessageElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-message": JSXElements.AppMessageAttributes;
    }
  }
  namespace JSXElements {
    export interface AppMessageAttributes extends HTMLAttributes {
      message?: any;
    }
  }
}


import {
  AppMessages as AppMessages
} from './components/app-messages/app-messages';

declare global {
  interface HTMLAppMessagesElement extends AppMessages, HTMLElement {
  }
  var HTMLAppMessagesElement: {
    prototype: HTMLAppMessagesElement;
    new (): HTMLAppMessagesElement;
  };
  interface HTMLElementTagNameMap {
    "app-messages": HTMLAppMessagesElement;
  }
  interface ElementTagNameMap {
    "app-messages": HTMLAppMessagesElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-messages": JSXElements.AppMessagesAttributes;
    }
  }
  namespace JSXElements {
    export interface AppMessagesAttributes extends HTMLAttributes {
      url?: string;
    }
  }
}


import {
  AppProfile as AppProfile
} from './components/app-profile/app-profile';

declare global {
  interface HTMLAppProfileElement extends AppProfile, HTMLElement {
  }
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };
  interface HTMLElementTagNameMap {
    "app-profile": HTMLAppProfileElement;
  }
  interface ElementTagNameMap {
    "app-profile": HTMLAppProfileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "app-profile": JSXElements.AppProfileAttributes;
    }
  }
  namespace JSXElements {
    export interface AppProfileAttributes extends HTMLAttributes {
      match?: MatchResults;
    }
  }
}


import {
  MyApp as MyApp
} from './components/my-app/my-app';

declare global {
  interface HTMLMyAppElement extends MyApp, HTMLElement {
  }
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };
  interface HTMLElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  interface ElementTagNameMap {
    "my-app": HTMLMyAppElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-app": JSXElements.MyAppAttributes;
    }
  }
  namespace JSXElements {
    export interface MyAppAttributes extends HTMLAttributes {
      
    }
  }
}

